SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, 
SUM(c.SALES * b.PRICE) AS 'TOTAL_SALES'
FROM AUTHOR a 
    INNER JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
    INNER JOIN BOOK_SALES c ON b.BOOK_ID = c.BOOK_ID
WHERE (c.SALES_DATE LIKE '2022-01%')
GROUP BY b.CATEGORY, b.AUTHOR_ID
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;