-- 코드를 입력하세요
SELECT A.AUTHOR_ID AS AUTHOR_ID,AUTHOR_NAME,CATEGORY,
SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID=B.AUTHOR_ID 
JOIN BOOK_SALES C
ON A.BOOK_ID=C.BOOK_ID
WHERE 1=1
AND DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-01'
GROUP BY AUTHOR_ID,AUTHOR_NAME,CATEGORY
ORDER BY A.AUTHOR_ID,CATEGORY DESC

