-- 코드를 작성해주세요
SELECT E.ID
FROM ECOLI_DATA E JOIN
(SELECT C.ID FROM ECOLI_DATA C JOIN
 (SELECT ID FROM ECOLI_DATA 
WHERE PARENT_ID IS NULL) D
 ON C.PARENT_ID=D.ID) B
 ON E.PARENT_ID=B.ID
 ORDER BY E.ID
 