-- 코드를 작성해주세요

/*
SELECT E.ID
FROM ECOLI_DATA E JOIN
(SELECT C.ID FROM ECOLI_DATA C JOIN
 (SELECT ID FROM ECOLI_DATA 
WHERE PARENT_ID IS NULL) D
 ON C.PARENT_ID=D.ID) B
 ON E.PARENT_ID=B.ID
 ORDER BY E.ID
*/

-- JOIN문 연달아 사용하기
SELECT G3.ID
FROM ECOLI_DATA G1
JOIN ECOLI_DATA G2 ON G1.ID=G2.PARENT_ID
JOIN ECOLI_DATA G3 ON G2.ID=G3.PARENT_ID
WHERE G1.PARENT_ID IS NULL
ORDER BY G3.ID

-- 재귀함수 이용하기