-- 코드를 작성해주세요
SELECT B.ITEM_ID AS ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO A JOIN ITEM_TREE B
ON A.ITEM_ID=B.ITEM_ID
WHERE 1=1
AND B.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID 
                      FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY B.ITEM_ID DESC