-- 코드를 작성해주세요
SELECT ID,IFNULL(CHILD_COUNTT,0) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN (SELECT PARENT_ID,COUNT(PARENT_ID) AS CHILD_COUNTT FROM ECOLI_DATA GROUP BY PARENT_ID) B
ON A.ID=B.PARENT_ID
ORDER BY ID