-- 코드를 입력하세요
SELECT A.PRODUCT_CODE AS PRODUCT_CODE,B.COUNT*A.PRICE AS SALES
FROM PRODUCT A,
(SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AS COUNT FROM OFFLINE_SALE GROUP BY PRODUCT_ID) B
WHERE 1=1
AND A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC