-- 코드를 입력하세요
/*DATEDIFF(END_DATE, START_DATE) 해당날짜를 포함해야하면 +1해준다.*/
/*날짜가 안겹치려면 11월이 시작하기도 전에 끝나버리는 경우 END_DATE<2022-11-01 AND 11월이 다 끝나고 나서야 시작하는 경우 START_DATE > 2022-11-30*/
/*정수 연산이나 반올림 처리 문제로 소수점이 남아 문제의 주의사항조건에 거릴 수 있으므로, ROUND() 함수 처리해준다.*/
SELECT A.CAR_ID AS CAR_ID,A.CAR_TYPE AS CAR_TYPE,
ROUND((DAILY_FEE*((100-DISCOUNT_RATE)*0.01))*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
JOIN (SELECT CAR_TYPE,DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '30일%' AND CAR_TYPE IN ('SUV','세단')) C
ON A.CAR_TYPE=C.CAR_TYPE
/*JOIN 연산을 무리하게 넣는 거보다 안되는 날짜를 NOT IN  하는 것도 방법*/
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE DATE(START_DATE)<='2022-11-30' AND DATE(END_DATE)>='2022-11-01')
GROUP BY CAR_ID,A.CAR_TYPE, FEE
HAVING FEE>=500000  AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC