-- 코드를 입력하세요
SELECT YEAR, MONTH,
GENDER, 
COUNT(B.USER_ID) AS USERS
FROM USER_INFO A JOIN (SELECT USER_ID,YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH
FROM ONLINE_SALE  GROUP BY USER_ID,YEAR,MONTH) B
ON A.USER_ID=B.USER_ID
WHERE 1=1
AND GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER