-- 코드를 입력하세요
/*SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE 1=1
AND ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)*/

SELECT B.ANIMAL_ID ANIMAL_ID,B.NAME NAME
FROM ANIMAL_OUTS B LEFT JOIN ANIMAL_INS A
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE 1=1
AND A.ANIMAL_ID IS NULL
;