-- 코드를 작성해주세요

WITH RECURSIVE COUNTGENERATION AS (
    SELECT ID,1 AS GEN
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
            UNION ALL
    SELECT E.ID,G.GEN+1 
    FROM ECOLI_DATA E
    JOIN COUNTGENERATION G ON E.PARENT_ID=G.ID
    )

SELECT COUNT(*) COUNT, GEN
FROM COUNTGENERATION
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM 
                 ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
                 GROUP BY GEN
                 ORDER BY GEN
