-- 코드를 입력하세요
/*SELECT A.NAME,A.DATETIME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE 1=1
AND B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME ASC
LIMIT; 3*/

SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A 
WHERE NOT EXISTS (SELECT 1 FROM ANIMAL_OUTS B
                             WHERE A.ANIMAL_ID=B.ANIMAL_ID)
ORDER BY A.DATETIME ASC
LIMIT 3