-- 코드를 입력하세요
SELECT A.PRODUCT_ID AS PRODUCT_ID,PRODUCT_NAME,PRICE*SUM(AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE 1=1
AND DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY PRODUCT_ID,PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID