-- 코드를 입력하세요
SELECT A.PRODUCT_ID,A.PRODUCT_NAME,(AMOUNT*PRICE) TOTAL_SALES
FROM FOOD_PRODUCT A JOIN 
(SELECT PRODUCT_ID,SUM(AMOUNT) AMOUNT FROM FOOD_ORDER 
WHERE PRODUCE_DATE>='2022-05-01' AND PRODUCE_DATE<'2022-06-01' GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID=B.PRODUCT_ID
GROUP BY A.PRODUCT_ID,A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC,A.PRODUCT_ID 
