-- 코드를 입력하세요
SELECT HISTORY_ID,
(CASE
WHEN DATE = 90
THEN FLOOR((DAILY_FEE*DISCOUNT*(DATEDIFF(END_DATE,START_DATE)+1)))
WHEN DATE = 30
THEN FLOOR((DAILY_FEE*DISCOUNT*(DATEDIFF(END_DATE,START_DATE)+1)))
WHEN DATE = 7
THEN FLOOR((DAILY_FEE*DISCOUNT*(DATEDIFF(END_DATE,START_DATE)+1)))
WHEN DATE=1 THEN DAILY_FEE*(DATEDIFF(END_DATE,START_DATE)+1)
END) AS FEE
FROM 
(SELECT CAR_ID,CAR_TYPE,DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE='트럭' GROUP BY CAR_ID,CAR_TYPE,DAILY_FEE) A JOIN 
(SELECT 
 (CASE 
 WHEN DATEDIFF(END_DATE,START_DATE)+1>=90
 THEN 90
 WHEN DATEDIFF(END_DATE,START_DATE)+1>=30
 THEN 30
 WHEN DATEDIFF(END_DATE,START_DATE)+1>=7
 THEN 7
 ELSE 1
 END) AS DATE,HISTORY_ID,CAR_ID,
 START_DATE,END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) B
ON A.CAR_ID=B.CAR_ID
LEFT JOIN (SELECT CAR_TYPE,
      (CASE 
      WHEN DURATION_TYPE LIKE '%7%'
      THEN 7
      WHEN DURATION_TYPE LIKE '%30%'
      THEN 30
      WHEN DURATION_TYPE LIKE '%90%'
      THEN 90
      ELSE NULL
      END) AS DURATION,
      (1-(DISCOUNT_RATE/100)) AS DISCOUNT
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' GROUP BY CAR_TYPE,DURATION,DISCOUNT) C
ON A.CAR_TYPE=C.CAR_TYPE
AND B.DATE=C.DURATION
ORDER BY FEE DESC,HISTORY_ID DESC




/*SELECT HISTORY_ID,
(CASE
WHEN DATEDIFF(END_DATE,START_DATE)+1 >= DURATION
THEN (DAILY_FEE*DISCOUNT*(DATEDIFF(END_DATE,START_DATE)+1))
WHEN DATEDIFF(END_DATE,START_DATE)+1 >=DURATION
THEN (DAILY_FEE*DISCOUNT*(DATEDIFF(END_DATE,START_DATE)+1))
WHEN DATEDIFF(END_DATE,START_DATE)+1 >=DURATION
THEN (DAILY_FEE*DISCOUNT*(DATEDIFF(END_DATE,START_DATE)+1))
WHEN DATEDIFF(END_DATE,START_DATE)+1<7 THEN DAILY_FEE*(DATEDIFF(END_DATE,START_DATE)+1)
END) AS FEE
FROM 
(SELECT CAR_ID,CAR_TYPE,DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE='트럭' GROUP BY CAR_ID,CAR_TYPE,DAILY_FEE) A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
ON A.CAR_ID=B.CAR_ID
JOIN (SELECT CAR_TYPE,
      (CASE 
      WHEN DURATION_TYPE LIKE '%7%'
      THEN 7
      WHEN DURATION_TYPE LIKE '%30%'
      THEN 30
      WHEN DURATION_TYPE LIKE '%90%'
      THEN 90
      END) AS DURATION,
      (1-(DISCOUNT_RATE/100)) AS DISCOUNT
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' GROUP BY CAR_TYPE,DURATION,DISCOUNT) C
ON A.CAR_TYPE=C.CAR_TYPE
GROUP BY HISTORY_ID,FEE
ORDER BY FEE DESC,HISTORY_ID DESC*/

