-- 코드를 입력하세요
SELECT A.FLAVOR
FROM
(SELECT FLAVOR,SUM(TOTAL_ORDER) SUMA FROM JULY GROUP BY FLAVOR) A
JOIN
(SELECT FLAVOR,SUM(TOTAL_ORDER) SUMB FROM FIRST_HALF GROUP BY FLAVOR) B
ON A.FLAVOR=B.FLAVOR
ORDER BY SUMA+SUMB DESC
LIMIT 3
