-- 코드를 작성해주세요
SELECT ID,EMAIL,FIRST_NAME,LAST_NAME
FROM (SELECT CATEGORY,CODE FROM SKILLCODES WHERE CATEGORY='Front End') A 
CROSS JOIN DEVELOPERS B
ON A.CODE&B.SKILL_CODE>0
GROUP BY ID,EMAIL,FIRST_NAME,LAST_NAME
ORDER BY ID