-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_BOARD A, USED_GOODS_USER B,
(SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES FROM USED_GOODS_BOARD
 WHERE STATUS='DONE'
GROUP BY WRITER_ID) C
WHERE 1=1
AND A.WRITER_ID =B.USER_ID
AND B.USER_ID = C.WRITER_ID
AND C.TOTAL_SALES >= 700000
GROUP BY C.WRITER_ID 
ORDER BY TOTAL_SALES ASC

