SELECT b.USER_ID, b.NICKNAME, SUM(a.PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD a INNER JOIN USED_GOODS_USER b 
ON a.WRITER_ID = b.USER_ID
WHERE STATUS = 'DONE'
GROUP BY a.WRITER_ID # 사람별 집계 => 그룹핑
HAVING SUM(a.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;