-- 코드를 작성해주세요
WITH COUNT_GRADE AS (
SELECT EMP_NO,
(CASE 
    WHEN AVG(SCORE)>=96
    THEN 'S'
    WHEN AVG(SCORE)>=90 AND AVG(SCORE)<96
    THEN 'A'
    WHEN AVG(SCORE)>=80 AND AVG(SCORE)<90
    THEN 'B'
    ELSE 'C'
    END) AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
),
/*UNION ALL은 아래 위로 데이터를 합치는 거기 때문에, SELECT문의 개수와 데이터 타입이 같아야한다.'*/
COUNT_BONUS AS(
SELECT A.EMP_NO AS EMP_NO,
    (CASE 
    WHEN GRADE='S'
    THEN SAL*0.2
    WHEN GRADE='A'
    THEN SAL*0.15
    WHEN GRADE='B'
    THEN SAL*0.1
    ELSE SAL*0
    END) AS BONUS, GRADE
    FROM HR_EMPLOYEES A JOIN COUNT_GRADE B
    ON A.EMP_NO=B.EMP_NO
)

SELECT A.EMP_NO,EMP_NAME,GRADE,BONUS
FROM HR_EMPLOYEES A JOIN COUNT_BONUS B
ON A.EMP_NO=B.EMP_NO
ORDER BY EMP_NO
