SELECT a.MEMBER_NAME, b.REVIEW_TEXT, DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') FROM MEMBER_PROFILE a 
    INNER JOIN REST_REVIEW b
ON a.MEMBER_ID = b.MEMBER_ID
WHERE b.MEMBER_ID IN (
    SELECT MEMBER_ID FROM 
        (SELECT MEMBER_ID FROM REST_REVIEW
         GROUP BY MEMBER_ID
         ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1
        ) AS t
    )
ORDER BY b.REVIEW_DATE, b.REVIEW_TEXT;