-- 코드를 작성해주세요
SELECT A.ITEM_ID,A.ITEM_NAME,A.RARITY 
FROM ITEM_INFO A, 
ITEM_TREE B,
(SELECT ITEM_ID 
 FROM ITEM_INFO
WHERE RARITY IN ('RARE')) D
WHERE 1=1
AND B.PARENT_ITEM_ID=D.ITEM_ID
AND A.ITEM_ID=B.ITEM_ID
ORDER BY A.ITEM_ID DESC

