SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY FROM ITEM_TREE a
INNER JOIN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
) b
  ON a.PARENT_ITEM_ID = b.ITEM_ID
INNER JOIN ITEM_INFO c
  ON a.ITEM_ID = c.ITEM_ID
ORDER BY c.ITEM_ID DESC;