-- 코드를 작성해주세요
SELECT C.ID,C.GENOTYPE,D.GENOTYPE
FROM ECOLI_DATA  C JOIN (SELECT DISTINCT B.PARENT_ID,A.GENOTYPE
FROM ECOLI_DATA A JOIN ECOLI_DATA B
ON A.ID=B.PARENT_ID) D
ON C.PARENT_ID=D.PARENT_ID
WHERE 1=1
AND D.GENOTYPE-(C.GENOTYPE&D.GENOTYPE)=0
ORDER BY C.ID
