-- 코드를 입력하세요
SELECT A.FLAVOR AS FLAVOR
FROM FIRST_HALF A JOIN ICECREAM_INFO B
ON A.FLAVOR=B.FLAVOR
WHERE 1=1
AND TOTAL_ORDER>3000
AND INGREDIENT_TYPE='fruit_based'
GROUP BY A.FLAVOR
ORDER BY TOTAL_ORDER DESC