-- 코드를 입력하세요
SELECT B.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID=B.CAR_ID
WHERE 1=1
AND CAR_TYPE='세단'
AND DATE_FORMAT(START_DATE,'%Y-%m')='2022-10'
GROUP BY B.CAR_ID
ORDER BY B.CAR_ID DESC