SELECT 
    a.ID,
    b.FISH_NAME,
    IFNULL(a.LENGTH, 10)
FROM FISH_INFO a
INNER JOIN FISH_NAME_INFO b
    ON a.FISH_TYPE = b.FISH_TYPE
WHERE (a.LENGTH, a.FISH_TYPE) IN (
    SELECT MAX(LENGTH), FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY a.ID;