SELECT SUM(b.SCORE), b.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
FROM HR_EMPLOYEES a INNER JOIN HR_GRADE b
ON a.EMP_NO = b.EMP_NO
WHERE b.YEAR = 2022
GROUP BY b.EMP_NO
ORDER BY SUM(b.SCORE) DESC 
LIMIT 1;