-- 코드를 입력하세요
SELECT 
 CONCAT(CONCAT_WS('/','','home','grep','src',A.BOARD_ID,FILE_ID),FILE_NAME,FILE_EXT) 
 AS FILE_PATCH
FROM USED_GOODS_FILE A,USED_GOODS_BOARD B
WHERE A.BOARD_ID=B.BOARD_ID
AND VIEWS=(SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
 ORDER BY FILE_ID DESC