-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY,MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A JOIN
(SELECT CATEGORY , MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT 
 GROUP BY CATEGORY) B
ON A.CATEGORY=B.CATEGORY
WHERE B.CATEGORY IN ('과자','국','김치','식용유')
AND PRICE = MAX_PRICE
ORDER BY PRICE DESC