-- 코드를 작성해주세요
SELECT 
CASE
WHEN MAX(IF(A.CATEGORY='Front End',1,0))=1
AND MAX(IF(A.NAME='Python',1,0))=1 THEN 'A'
WHEN MAX(IF(A.NAME='C#',1,0))=1 THEN 'B'
WHEN MAX(IF(A.CATEGORY='Front End',1,0))=1 THEN 'C'
END
AS GRADE,
ID,
EMAIL
FROM SKILLCODES A JOIN DEVELOPERS B
ON (A.CODE&B.SKILL_CODE)>0
GROUP BY ID
HAVING GRADE IS NOT NULL
ORDER BY GRADE,ID
